# Bu dosya, Prometheus'un hangi hedefleri (endpoint)
# izleyeceğini (scrape) belirler.

global:
  scrape_interval: 15s # Varsayılan olarak her 15 saniyede bir veri çek.

# İzlenecek hedeflerin (uygulamaların) listesi
scrape_configs:
  # 1. İş: Prometheus'un kendisini izlemesi (iyi bir pratiktir)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. İş: Bizim Spring Boot uygulamamız
  - job_name: 'spring-boot-app'
    # Spring Boot Actuator'ün metrikleri sunduğu yol
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal', Docker container'ından host makinesine
      # (yani 'localhost'a) erişmek için kullanılan özel bir DNS adıdır.
      # Spring Boot uygulamamızın 8080 portunda çalıştığını varsayıyoruz.
      - targets: ['host.docker.internal:8080']
