package de.blinkt.openvpn.core;

public enum ConnectionStatus {
    LEVEL_CONNECTED,
    LEVEL_NOTCONNECTED,
    LEVEL_AUTH_FAILED,
    LEVEL_NONETWORK,
    LEVEL_CONNECTING_NO_SERVER_REPLY_YET,
    LEVEL_CONNECTING_SERVER_REPLIED,
    LEVEL_WAITING_FOR_USER_INPUT
}
